- name: Add cgroup parameters to /boot/cmdline.txt
  hosts: all
  become: true
  tasks:
    - name: Append cgroup parameters to /boot/cmdline.txt
      lineinfile:
        path: /boot/cmdline.txt
        regexp: '^(.*)$'
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
        backrefs: true
        state: present
